apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nsa
spec:
  destination:
    name: ''
    namespace: nsa
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/NSA
    repoURL: 'https://github.com/seb34000/T-NSA810'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
