# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  ## name of ConfigMap. This will be referred from volume definition
  name: db-config
  labels:
    app: db
data:
  ## default_auth is the name of config. This will be referred from volume mount definition
  db-config.sql: |-
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
