apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/t-nsa810-default: "true"
        io.kompose.service: front
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: localhost:3000
          image: front
          name: front
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
