apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  template:
    metadata:
      labels:
        io.kompose.network/t-nsa810-default: "true"
        io.kompose.service: front
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://api:3000
          image: front:1.0
          imagePullPolicy: IfNotPresent
          name: front
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      restartPolicy: Always
